on: [push]

jobs:
  restroom_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Hello world action step
        uses: ./
      - name: Install curl
        run: sudo apt install curl
      - name: Try to fetch
        run: curl http://localhost:3000/api/test
